{% set version = "0.4" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcppprogress
  version: {{ version|replace("-", "_") }}

source:
  fn: RcppProgress_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/RcppProgress_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/RcppProgress/RcppProgress_{{ version }}.tar.gz
  sha256: 3b1ecc82ced98eb481819a28737dac3658586e11ad16a92abd14c4649ae15e25

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rcpp >=0.9.4
    - r-devtools
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp >=0.9.4
    - r-devtools

test:
  commands:
    - $R -e "library('RcppProgress')"  # [not win]
    - "\"%R%\" -e \"library('RcppProgress')\""  # [win]

about:
  home: https://github.com/kforner/rcpp_progress
  license: GPL-3
  summary: Allows to display a progress bar in the R console for long running computations taking
    place in c++ code, and support for interrupting those computations even in multithreaded
    code, typically using OpenMP.
  license_family: GPL

extra:
  recipe-maintainers:
    - bgruening
    - daler
    - johanneskoester
    - rvalieris
