{% set version = "0.4.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcppprogress
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppProgress_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppProgress/RcppProgress_{{ version }}.tar.gz
  sha256: b1624b21b7aeb1dafb30f092b2a4bef4c3504efd2d6b00b2cdf55dc9df194b48

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('RcppProgress')"           # [not win]
    - "\"%R%\" -e \"library('RcppProgress')\""  # [win]

about:
  home: https://github.com/kforner/rcpp_progress
  license: GPL-3.0-or-later
  summary: Allows to display a progress bar in the R console for long running computations taking
    place in c++ code, and support for interrupting those computations even in multithreaded
    code, typically using OpenMP.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris

# Package: RcppProgress
# Maintainer: Karl Forner <karl.forner@gmail.com>
# License: GPL (>= 3)
# Title: An Interruptible Progress Bar with OpenMP Support for C++ in R Packages
# Type: Package
# LazyLoad: yes
# Author: Karl Forner <karl.forner@gmail.com>
# Description: Allows to display a progress bar in the R console for long running computations taking place in c++ code, and support for interrupting those computations even in multithreaded code, typically using OpenMP.
# URL: https://github.com/kforner/rcpp_progress
# BugReports: https://github.com/kforner/rcpp_progress/issues
# Version: 0.4.1
# Date: 2018-05-11
# Suggests: RcppArmadillo, devtools, roxygen2, testthat
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-05-11 13:15:30 UTC; karl
# Repository: CRAN
# Date/Publication: 2018-05-11 14:46:14 UTC
