{% set version = "0.4" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcppprogress
  version: {{ version|replace("-", "_") }}

source:
  fn: RcppProgress_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/RcppProgress_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/RcppProgress/RcppProgress_{{ version }}.tar.gz
  sha256: 706e14360dbc5976db05c2ac6692c3279c0f8c95e72bf9d4becd9e1348025e3e

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcpp >=0.9.4
    - r-devtools

  run:
    - r-base
    - r-rcpp >=0.9.4
    - r-devtools

test:
  commands:
    - $R -e "library('RcppProgress')"  # [not win]
    - "\"%R%\" -e \"library('RcppProgress')\""  # [win]

about:
  home: https://github.com/kforner/rcpp_progress
  license: GPL-3
  summary: Allows to display a progress bar in the R console for long running computations taking
    place in c++ code, and support for interrupting those computations even in multithreaded
    code, typically using OpenMP.
  license_family: GPL

extra:
  recipe-maintainers:
    - dpryan79
    - bgruening
    - daler
    - johanneskoester
    - rvalieris
