appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: LWgvo0RCujhLEAr0LNwc0LHz0LWV0wo/WxTT2ce4hhribP009IPVQ9XmnX45fobxUDLh9S5RmQTM8y5UM8Z4Ud2urtEvgMvjpSYO9pfAm9xdiAZsf3uPEQ1EQSBSbFphI6PZZGdb2veajaa8R0fLS5q7eTKvBjXlK665DUg2SYnT/BzbB+9P62GrJinEm4OJEUKCJoq7p4o9AGaEXyD1lh3wCSHHJSbCrrBgM1uobUzJQSIbw4vwSxuTa9GX50lar2rCHbRVhwxnp3769PlNi8XaP/Vl5iKEPwZXFcTdK05y3oXOq4c0WKb+Y5YHyadG4Mo4ohNCSQ7B7ygMRERIPSV01Tpaqf6jVKXIlROlrtgzL7622Wn0y4ng2Sl5vuKSjC+o7aGGw+llnXPAx2HEmDSW8gLMppo2jnJCjWdZBhy0tHcNTtWXUTcZ8Ejqsf1MCndfjeZmG0ZozfKkUGkq/4sBCK1IY0EKbRPrD7EARKD9pk1gYaIXeBxyD2LCLFVW6dgsRS84nDepIqY1FAPWCPJCGRExtNaVr47skusUN1IZ6LVfJ+na2wfpjNO6Eh6fKxELqaBhPNFur90fhI7zsPhGsl8iiw9O1TC34zL3KBj8d/lvSUEaMivQLA1pm2TgbY6NrCKyiBPwPleU1HAg1M7cVPWxPmM4h4f41QJUpMA=
conda_forge_output_validation: false
